export const types = [
  'Artifact',
  'Conspiracy',
  'Creature',
  'Enchantment',
  'Instant',
  'Land',
  'Phenomenon',
  'Plane',
  'Planeswalker',
  'Scheme',
  'Sorcery',
  'Tribal',
  'Vanguard',
];

export const sets = [
  'Limited Edition Alpha',
  'Limited Edition Beta',
  'Unlimited Edition',
  'Revised Edition',
  'Fourth Edition',
  'Fifth Edition',
  'Classic Sixth Edition',
  'Seventh Edition',
  'Eighth Edition',
  'Ninth Edition',
  'Magic 2010',
  'Magic 2011',
  'Magic 2012',
  'Magic 2013',
  'Magic 2014',
  'Magic 2015',
  'Magic Origins',
  'Core Set 2019',
  'Core Set 2020',
  'Core Set 2021',
  'Arabian Nights',
  'Antiquities',
  'Legends',
  'The Dark',
  'Fallen Empires',
  'Ice Age',
  'Homelands',
  'Alliances',
  'Mirage',
  'Visions',
  'Weatherlight',
  'Tempest',
  'Stronghold',
  'Exodus',
  "Urza's Saga",
  "Urza's Legacy",
  "Urza's Destiny",
  'Mercadian Masques',
  'Nemesis',
  'Prophecy',
  'Invasion',
  'Planseshift',
  'Apocalaypse',
  'Odyssey',
  'Torment',
  'Judgment',
  'Onslaught',
  'Legions',
  'Scourge',
  'Mirrodin',
  'Darksteel',
  'Fifth Dawn',
  'Champions of Kamigawa',
  'Betrayers of Kamigawa',
  'Saviors of Kamigawa',
  'Ravcnica: City of Guilds',
  'Guildpact',
  'Dissension',
  'Coldsnap',
  'Time Spiral',
  'Planar Chaos',
  'Future Sight',
  'Lorwyn',
  'Morningtide',
  'Shadowmoor',
  'Eventide',
  'Shards of Alara',
  'Conflux',
  'Alara Reborn',
  'Zendikar',
  'Wolrdwake',
  'Rise of Eldrazi',
  'Scars of Mirrodin',
  'Mirrodin Besieged',
  'New Phyrexia',
  'Innistrad',
  'Dark Ascension',
  'Avacyn Restored',
  'Return to Ravnica',
  'Gatecrash',
  "Dragon's Maze",
  'Theros',
  'Born of the Gods',
  'Journey into Nyx',
  'Khans of Tarkir',
  'Fate Reforged',
  'Dragons of Tarkir',
  'Battle for Zendikar',
  'Oath of the Gatewatch',
  'Shadows over Innistrad',
  'Eldritch Moon',
  'Kaladesh',
  'Aether Revolt',
  'Amonkhet',
  'Hour of Devastation',
  'Ixalan',
  'Rivals of Ixalan',
  'Dominaria',
  'Guilds of Ravnica',
  'Ravnica Allegiance',
  'War of the Spark',
  'Throne of Eldraine',
  'Theros Beyond Death',
  'Ikoria: Lair of Behemoths',
  'Zendikar Rising',
  'Kaldheim',
  'Strixhaven: School of Mages',
  'Adventures in the Forgotten Realms',
  'Innistrad: Midnight Hunt',
  'Innistrad: Crimson Vow',
  'Kamigawa: Neon Dynasty',
  'Streets of New Capenna',
  'Modern Horizons',
  'Modern Horizons 2',
];
